/* Catálogo de peptídeos — mesmos dados publicados em peptideoevida.com.br,
   reorganizados para o novo front-end (paginado, sem framework, sem travar). */

const WHATSAPP_NUMBER = "5511947384628";

/* vialSize (mg), targetDose (mcg, valor inicial sugerido na calculadora), diluent (mL) */
const CALC_CONFIG = {
  bpc157: { vialSize: 5, targetDose: 250, diluent: 2 },
  tb500: { vialSize: 5, targetDose: 2000, diluent: 2 },
  ipamorelin: { vialSize: 2, targetDose: 150, diluent: 2 },
  semaglutide: { vialSize: 5, targetDose: 250, diluent: 2 },
  dihexa: { vialSize: 30, targetDose: 10000, diluent: 2 },
  "ghk-cu": { vialSize: 50, targetDose: 1000, diluent: 2 },
  epithalon: { vialSize: 10, targetDose: 5000, diluent: 2 },
  pt141: { vialSize: 10, targetDose: 1000, diluent: 2 },
  tirzepatide: { vialSize: 5, targetDose: 2500, diluent: 2 },
  cjc1295: { vialSize: 2, targetDose: 150, diluent: 2 },
  aod9604: { vialSize: 5, targetDose: 300, diluent: 2 },
  melanotanii: { vialSize: 10, targetDose: 250, diluent: 2 },
  semax: { vialSize: 10, targetDose: 200, diluent: 2 },
  selank: { vialSize: 10, targetDose: 200, diluent: 2 },
  motsc: { vialSize: 10, targetDose: 10000, diluent: 2 },
  tesamorelin: { vialSize: 2, targetDose: 1000, diluent: 2 },
  ll37: { vialSize: 5, targetDose: 250, diluent: 2 },
  cerebrolysin: { vialSize: 10, targetDose: 5000, diluent: 10 },
  kisspeptin10: { vialSize: 10, targetDose: 200, diluent: 2 },
  ara290: { vialSize: 16, targetDose: 4000, diluent: 2 },
  thymosinalpha1: { vialSize: 10, targetDose: 1500, diluent: 2 },
  kpv: { vialSize: 5, targetDose: 300, diluent: 2 },
  hghfrag176191: { vialSize: 5, targetDose: 250, diluent: 2 },
  dsip: { vialSize: 2, targetDose: 100, diluent: 2 },
  igf1lr3: { vialSize: 1, targetDose: 30, diluent: 2 },
  pegmgf: { vialSize: 2, targetDose: 200, diluent: 2 },
  ghrp6: { vialSize: 5, targetDose: 100, diluent: 2 },
  ghrp2: { vialSize: 5, targetDose: 100, diluent: 2 },
  sermorelin: { vialSize: 2, targetDose: 200, diluent: 2 },
  retatrutide: { vialSize: 5, targetDose: 2000, diluent: 2 },
  follistatin344: { vialSize: 1, targetDose: 100, diluent: 2 },
  adipotide: { vialSize: 5, targetDose: 500, diluent: 2 },
  vip: { vialSize: 5, targetDose: 50, diluent: 2 },
};

const PRODUCTS = [
  {
    id: "bpc157", name: "BPC-157",
    aliases: ["Body Protection Compound 157", "Pentadecapeptide BPC 157"],
    diagnoses: "tendinite.tendinopathy.ligamento.ligament.lesão muscular.muscle injury.úlcera gástrica.gastric ulcer.colite.colitis.inflamação.inflammation.cicatrização.wound healing.síndrome do intestino irritável.ibs.doença inflamatória intestinal.crohn.artrite.arthritis.recuperação muscular.dor articular.joint pain.reparo tecidual.tissue repair.gastrite.machucado.dor no ombro.dor no joelho.rasgo no músculo.gastrite nervosa.azia crônica.trauma musculoesquelético.lesão condral.lesão ligamentar.refluxo gastroesofágico.drge.lesão de cartilagem".split("."),
    mechanism: "Peptídeo derivado da proteína de proteção gástrica humana. Estimula a angiogênese, promove síntese de colágeno, modula óxido nítrico e ativa fatores de crescimento como EGF e VEGF. Tem efeito gastroprotetor direto sobre a mucosa gástrica.",
    dosage: "200–500 mcg/dia", route: "Subcutânea ou intramuscular", cycle: "4–12 semanas",
    benefits: ["Aceleração da cicatrização de tendões e ligamentos", "Proteção e reparo da mucosa gastrointestinal", "Efeito anti-inflamatório sistêmico", "Neuroproteção e suporte cognitivo", "Melhora da mobilidade articular"],
    sideEffects: ["Tontura leve (relatada em doses altas)", "Náusea temporária", "Vermelhidão no local da injeção"],
    contraindications: ["Neoplasias ativas (estímulo angiogênico)", "Gravidez e lactação", "Hipersensibilidade ao composto"],
    evidenceLevel: "Pré-clínico robusto / Clínico emergente",
    pricing: { averageMonthlyBRL: 420, averageMonthlyUSD: 85, rangeMinBRL: 280, rangeMaxBRL: 680, unit: "frasco 5mg liofilizado", source: "Estimativa baseada em farmácias de manipulação e fornecedores especializados (2025)" },
    references: ["Sikiric P et al. (2018). Brain-gut Axis and Pentadecapeptide BPC 157. Curr Neuropharmacol.", "Chang CH et al. (2011). The promoting effect of pentadecapeptide BPC 157 on tendon healing. Acta Histochem."],
  },
  {
    id: "tb500", name: "TB-500",
    aliases: ["Thymosin Beta-4", "Tβ4"],
    diagnoses: "lesão muscular.muscle injury.tendinite.tendinopathy.recuperação esportiva.athletic recovery.fibrose cardíaca.cardiac fibrosis.cicatrização.wound healing.inflamação crônica.chronic inflammation.alopecia.queda de cabelo.hair loss.reparo tecidual.tissue repair.lesão esportiva.sports injury.ruptura muscular.distensão.estiramento.rompimento.musculo rasgado.careca.caindo cabelo.recuperação rápida.inflamação nas juntas.miopatia.fibrose tecidual.doença isquêmica do coração.alopecia androgenética.reparo endotelial".split("."),
    mechanism: "Fragmento sintético da Timosina Beta-4, proteína endógena de 43 aminoácidos. Promove migração e diferenciação celular, regula actina, estimula angiogênese, reduz inflamação via downregulation de NF-κB e promove regeneração tecidual.",
    dosage: "2–2,5 mg duas vezes por semana", route: "Subcutânea ou intramuscular", cycle: "4–6 semanas (loading) + 2–4 semanas (manutenção)",
    benefits: ["Reparo acelerado de tecidos moles", "Redução significativa do tempo de recuperação pós-lesão", "Efeito anti-inflamatório potente", "Potencial cardioprotetor", "Estímulo ao crescimento capilar"],
    sideEffects: ["Fadiga transitória nas primeiras doses", "Dor de cabeça leve", "Reação local na injeção"],
    contraindications: ["Câncer ativo (potencial proliferativo)", "Gravidez", "Doença autoimune descontrolada"],
    evidenceLevel: "Pré-clínico avançado / Fase II clínica (cardíaco)",
    pricing: { averageMonthlyBRL: 580, averageMonthlyUSD: 115, rangeMinBRL: 380, rangeMaxBRL: 900, unit: "frasco 5mg liofilizado", source: "Estimativa baseada em fornecedores internacionais e nacionais (2025)" },
    references: ["Goldstein AL et al. (2012). Thymosin β4: A multifunctional regenerative peptide. Expert Opin Biol Ther.", "Mora CA et al. (2012). Thymosin β4 and Wound Healing. Vitamins & Hormones."],
  },
  {
    id: "ipamorelin", name: "Ipamorelin",
    aliases: ["NNC 26-0161"],
    diagnoses: "deficiência de gh.gh deficiency.envelhecimento.aging.sarcopenia.perda muscular.muscle loss.recuperação pós-operatória.post-op recovery.obesidade.obesity.baixa densidade óssea.low bone density.osteoporose.osteoporosis.distúrbio do sono.sleep disorder.fadiga crônica.chronic fatigue.longevidade.longevity.composição corporal.body composition.barriga grande.perder gordura.dormir mal.insônia leve.velhice.querer ficar forte.deficiência de somatotropina.hipopituitarismo.síndrome da fragilidade.osteopenia.distúrbios do ritmo circadiano.sarcopenia senil".split("."),
    mechanism: "Secretagogo de hormônio do crescimento seletivo e mimético da grelina. Liga-se ao receptor GHSR-1a na hipófise, estimulando liberação pulsátil de GH sem impactar cortisol ou prolactina. Ação limpa e seletiva.",
    dosage: "100–300 mcg/dia (preferencialmente à noite)", route: "Subcutânea", cycle: "8–16 semanas",
    benefits: ["Aumento da produção endógena de GH", "Melhora da composição corporal (redução de gordura, aumento de massa magra)", "Melhora da qualidade do sono", "Fortalecimento ósseo", "Recuperação acelerada pós-cirurgia"],
    sideEffects: ["Rubor facial leve", "Sensação de formigamento", "Retenção hídrica discreta", "Hipoglicemia leve em jejum prolongado"],
    contraindications: ["Neoplasias GH-dependentes", "Diabetes não controlado", "Retinopatia diabética ativa"],
    evidenceLevel: "Fase II/III clínica",
    pricing: { averageMonthlyBRL: 350, averageMonthlyUSD: 70, rangeMinBRL: 220, rangeMaxBRL: 550, unit: "frasco 2mg liofilizado", source: "Estimativa baseada em farmácias de manipulação brasileiras (2025)" },
    references: ["Raun K et al. (1998). Ipamorelin, a new growth-hormone-releasing peptide. Eur J Endocrinol.", "Johansen PB et al. (1999). Ipamorelin, a specific GH secretagogue. Growth Horm IGF Res."],
  },
  {
    id: "semaglutide", name: "Semaglutida",
    aliases: ["Semaglutide", "Ozempic", "Wegovy", "GLP-1 agonist"],
    diagnoses: "obesidade.obesity.diabetes tipo 2.type 2 diabetes.sobrepeso.overweight.controle glicêmico.glycemic control.síndrome metabólica.metabolic syndrome.resistência à insulina.insulin resistance.emagrecimento.weight loss.hiperglicemia.gordice.engordar muito.açúcar alto.pré-diabetes.vontade de comer doce.fome toda hora.síndrome plurimetabólica.esteatose hepática não alcoólica.nash.intolerância à glicose.hiperinsulinemia.fígado gorduroso".split("."),
    mechanism: "Análogo do GLP-1 (peptídeo semelhante ao glucagon-1) com meia-vida de ~7 dias. Estimula secreção de insulina glicose-dependente, inibe glucagon, retarda esvaziamento gástrico e atua no hipotálamo promovendo saciedade e redução do apetite.",
    dosage: "0,25 mg/semana (início) → até 2,4 mg/semana (Wegovy)", route: "Subcutânea (caneta injetora)", cycle: "Uso contínuo (crônico)",
    benefits: ["Redução média de 15–17% do peso corporal", "Controle glicêmico superior (redução HbA1c ~1,8%)", "Redução de risco cardiovascular documentada", "Melhora de marcadores metabólicos", "Efeito neuroprotetor emergente"],
    sideEffects: ["Náusea e vômito (especialmente no início)", "Diarreia ou constipação", "Pancreatite (raro)", "Risco teórico de carcinoma medular de tireoide (animais)"],
    contraindications: ["Neoplasia endócrina múltipla tipo 2 (NEM2)", "Carcinoma medular de tireoide pessoal ou familiar", "Pancreatite crônica grave", "Gravidez"],
    evidenceLevel: "Aprovado FDA/ANVISA — Evidência clínica de alto nível (Fase III)",
    pricing: { averageMonthlyBRL: 1200, averageMonthlyUSD: 240, rangeMinBRL: 850, rangeMaxBRL: 2100, unit: "caneta injetora 0,5ml (4 doses/semana)", source: "Tabela ANVISA/CMED e preços de mercado farmacêutico (2025)" },
    references: ["Wilding JPH et al. (2021). Once-Weekly Semaglutide in Adults with Overweight or Obesity. NEJM.", "Marso SP et al. (2016). Semaglutide and Cardiovascular Outcomes. NEJM."],
  },
  {
    id: "dihexa", name: "Dihexa",
    aliases: ["PNB-0408", "N-hexanoic-Tyr-Ile-(6) aminohexanoic amide"],
    diagnoses: "declínio cognitivo.cognitive decline.alzheimer.demência.dementia.nebulosidade mental.brain fog.parkinson.neuroproteção.neuroprotection.depressão.depression.déficit de memória.memory deficit.performance cognitiva.cognitive performance.esquecimento.cabeça fraca.não lembra nada.falta de foco.dificuldade de aprendizado.demência senil.doença de alzheimer precoce.comprometimento cognitivo leve.transtorno neurocognitivo.neurodegeneração.TDAH.déficit de atenção".split("."),
    mechanism: "Peptidomimético derivado da angiotensina IV. Superativa o sistema HGF/c-Met, promovendo crescimento de sinapses dendríticas, formação de novas conexões neurais e neuroproteção. Estimula BDNF e NGF, fatores essenciais para plasticidade neural.",
    dosage: "10–30 mg/dia (sublingual ou oral)", route: "Oral (sublingual ou cápsula) / Tópico nasal", cycle: "4–8 semanas (ciclos com intervalos)",
    benefits: ["Melhora significativa de memória e aprendizado", "Formação de novas sinapses (sinaptogênese)", "Efeito 10.000x mais potente que o Dilantin em modelos animais", "Neuroproteção em modelos de Alzheimer", "Clareza mental e desempenho cognitivo"],
    sideEffects: ["Dados de segurança humana ainda limitados", "Possível ansiedade em doses altas", "Potencial pró-angiogênico (cautela em câncer)"],
    contraindications: ["Neoplasias ativas", "Gravidez", "Dados de segurança insuficientes para uso crônico"],
    evidenceLevel: "Pré-clínico (roedor) — uso humano off-label experimental",
    pricing: { averageMonthlyBRL: 750, averageMonthlyUSD: 150, rangeMinBRL: 500, rangeMaxBRL: 1300, unit: "frasco 30mg / cápsulas", source: "Fornecedores especializados internacionais (2025)" },
    references: ["McCoy AT et al. (2013). Evaluation of HGF/c-Met System by Dihexa. J Pharmacol Exp Ther.", "Benoist CC et al. (2011). Facilitation of hippocampal synaptogenesis and memory. J Pharmacol Exp Ther."],
  },
  {
    id: "ghk-cu", name: "GHK-Cu",
    aliases: ["Copper Peptide", "GHK Copper"],
    diagnoses: "pele flacida.pele flácida.rugas.envelhecimento da pele.unhas fracas.unhas quebradiças.queda de cabelo.calvície.alopecia.cicatrização.manchas.saúde capilar.colágeno.pele caindo.cara enrugada.unha quebrando.cabelo fino.espinhas e manchas.ferida que não fecha.rugas profundas.flacidez dérmica.alopecia areata.dermatite de contato.cicatriz hipertrófica.fotoenvelhecimento.estrias".split("."),
    mechanism: "Peptídeo de cobre natural que promove a síntese de colágeno e elastina, atua como potente antioxidante e anti-inflamatório, estimula o crescimento capilar e repara tecidos.",
    dosage: "1-2 mg/dia (subcutânea) ou uso tópico cremes", route: "Subcutânea ou Tópico", cycle: "4-12 semanas",
    benefits: ["Aumento da firmeza e elasticidade da pele", "Estímulo do crescimento capilar (comparável ao minoxidil)", "Fortalecimento significativo de unhas e pele", "Redução de linhas finas, manchas e rugas"],
    sideEffects: ["Dor e vermelhidão no local da injeção (injetável)", "Possível irritação leve (tópico)"],
    contraindications: ["Sensibilidade ao cobre", "Doença de Wilson"],
    evidenceLevel: "Estudos clínicos e cosméticos consolidados",
    pricing: { averageMonthlyBRL: 450, averageMonthlyUSD: 90, rangeMinBRL: 250, rangeMaxBRL: 700, unit: "frasco 50mg", source: "Mercado magistral (2025)" },
    references: ["Pickart L et al. (2008). GHK-Cu in skin remodeling and healing."],
  },
  {
    id: "epithalon", name: "Epitalon",
    aliases: ["Epithalone", "Epithalamin", "Ala-Glu-Asp-Gly"],
    diagnoses: "envelhecimento.aging.longevidade.longevity.distúrbio do sono.sleep disorder.insônia.insomnia.imunodeficiência.immunodeficiency.retinite pigmentosa.retinitis pigmentosa.degeneração macular.macular degeneration.fadiga.fatigue.estresse oxidativo.oxidative stress.senescência celular.cellular senescence.visão.olhos.cegueira noturna.melhorar visão.saúde ocular.ritmo circadiano.dormir melhor.rejuvenescer.células velhas.vista fraca.doença no olho.catarata.glaucoma.retina".split("."),
    mechanism: "Tetrapeptídeo sintético que ativa a telomerase, alongando os telômeros. Regula a melatonina, normaliza os ritmos circadianos, rejuvenesce células e tem fortíssimo impacto na restauração da retina e tecidos oculares.",
    dosage: "5–10 mg/dia por 10–20 dias", route: "Subcutânea", cycle: "Ciclos de 10–20 dias, 1–2x por ano",
    benefits: ["Potencial extensão de telômeros (anti-aging profundo)", "Melhora drástica do ritmo circadiano e sono profundo", "Tratamento comprovado para Retinite Pigmentosa e degenerações oculares", "Imunomodulação e resistência celular"],
    sideEffects: ["Geralmente excepcionalmente bem tolerado", "Sonhos vívidos (relato anedótico)"],
    contraindications: ["Cânceres muito avançados (devido à ativação de telomerase)", "Gravidez"],
    evidenceLevel: "Estudos observacionais humanos robustos (Rússia/Leste Europeu)",
    pricing: { averageMonthlyBRL: 520, averageMonthlyUSD: 104, rangeMinBRL: 300, rangeMaxBRL: 900, unit: "frasco 10mg", source: "Importação" },
    references: ["Khavinson VK et al. (2002). Peptide regulation of ageing."],
  },
  {
    id: "pt141", name: "PT-141",
    aliases: ["Bremelanotide", "Vyleesi"],
    diagnoses: ["disfunção erétil", "erectile dysfunction", "disfunção sexual feminina", "female sexual dysfunction", "libido baixa", "low libido", "disfunção sexual", "sexual dysfunction", "hipoatividade sexual", "impotência", "falta de tesão", "não sobe", "frigidez", "desejo sexual", "sexo", "impotência sexual", "falta de vontade", "melhorar sexo", "viagra"],
    mechanism: "Agonista dos receptores de melanocortina. Diferente do Viagra que age nos vasos sanguíneos, o PT-141 age diretamente no sistema nervoso central (cérebro) acendendo o desejo sexual e a excitação real.",
    dosage: "1–2 mg (uso pontual, 45 min antes)", route: "Subcutânea ou intranasal", cycle: "Uso pontual (máx 1x/72h)",
    benefits: ["Aumento real do desejo sexual em homens e mulheres", "Melhora da função erétil via estímulo neural", "Eficaz em casos onde inibidores de PDE5 (Viagra/Cialis) falham", "Aprovado pelo FDA para mulheres (Vyleesi)"],
    sideEffects: ["Náusea temporária (muito comum)", "Rubor facial", "Pico de pressão arterial"],
    contraindications: ["Hipertensão não controlada", "Doença cardiovascular grave"],
    evidenceLevel: "FDA aprovado (mulheres) / Fase III (homens)",
    pricing: { averageMonthlyBRL: 680, averageMonthlyUSD: 136, rangeMinBRL: 450, rangeMaxBRL: 1200, unit: "frasco 10mg", source: "Importação" },
    references: ["Diamond LE et al. (2004). Double-blind evaluation of PT-141."],
  },
  {
    id: "tirzepatide", name: "Tirzepatida",
    aliases: ["Tirzepatide", "Mounjaro", "Zepbound", "GLP-1", "GIP"],
    diagnoses: "obesidade.obesity.diabetes tipo 2.type 2 diabetes.sobrepeso.overweight.controle glicêmico.glycemic control.síndrome metabólica.metabolic syndrome.resistência à insulina.insulin resistance.emagrecimento.weight loss.hiperglicemia.gordice.engordar muito.açúcar alto.pré-diabetes.vontade de comer doce.fome toda hora.síndrome plurimetabólica.esteatose hepática não alcoólica.nash.intolerância à glicose.hiperinsulinemia.fígado gorduroso.perda de peso severa.obesidade mórbida.emagrecer rápido".split("."),
    mechanism: "Primeiro agonista duplo (co-agonista) dos receptores GIP e GLP-1. O GLP-1 retarda o esvaziamento gástrico e reduz o apetite, enquanto o GIP potencializa a resposta à insulina, melhora o metabolismo lipídico e atua nos centros de recompensa do cérebro. Efeito sinérgico superior à Semaglutida isolada.",
    dosage: "2,5 mg a 15 mg/semana (aumento gradual de 4 em 4 semanas)", route: "Subcutânea (caneta injetora)", cycle: "Uso contínuo (crônico)",
    benefits: ["Perda de peso recorde na classe (média de até 22,5% do peso corporal em estudos)", "Controle glicêmico excepcional e rápido", "Melhora agressiva no perfil lipídico e pressão arterial", "Redução acentuada da esteatose hepática (gordura no fígado)"],
    sideEffects: ["Náusea, diarreia e vômitos (frequentes nas mudanças de dose)", "Desconforto gastrointestinal e empachamento", "Risco potencial de pancreatite", "Risco teórico de tumores de células C da tireoide (modelo animal)"],
    contraindications: ["Histórico de carcinoma medular de tireoide (CMT)", "Síndrome de neoplasia endócrina múltipla tipo 2 (NEM2)", "Gravidez e lactação"],
    evidenceLevel: "Aprovado FDA/ANVISA — Padrão Ouro Atual (Fase III SURMOUNT)",
    pricing: { averageMonthlyBRL: 3200, averageMonthlyUSD: 1000, rangeMinBRL: 2500, rangeMaxBRL: 4500, unit: "caneta injetora 4 doses", source: "Farmácias comerciais (2025)" },
    references: ["Jastreboff AM et al. (2022). Tirzepatide Once Weekly for the Treatment of Obesity. NEJM."],
  },
  {
    id: "cjc1295", name: "CJC-1295",
    aliases: ["Mod GRF 1-29", "CJC 1295 no DAC"],
    diagnoses: ["anti-aging", "envelhecimento", "sarcopenia", "perda muscular", "deficiência de gh", "gh deficiency", "recuperação esportiva", "qualidade do sono", "dormir mal", "rejuvenescimento", "anabolismo"],
    mechanism: "Análogo do GHRH (Hormônio Liberador de Hormônio do Crescimento). Estimula a liberação contínua e natural de GH pela hipófise, sem os picos não fisiológicos. Muitas vezes usado em sinergia com o Ipamorelin.",
    dosage: "100–300 mcg/dia", route: "Subcutânea", cycle: "12–16 semanas",
    benefits: ["Aumento prolongado dos níveis de GH e IGF-1", "Maior síntese proteica e hipertrofia muscular", "Redução de gordura corporal", "Melhora exponencial no sono profundo (REM)"],
    sideEffects: ["Rubor facial passageiro", "Retenção hídrica leve", "Sensibilidade no local da injeção"],
    contraindications: ["Câncer ativo", "Histórico familiar de tumores hipofisários"],
    evidenceLevel: "Ensaios clínicos (Fase II) e amplo uso off-label",
    pricing: { averageMonthlyBRL: 400, averageMonthlyUSD: 80, rangeMinBRL: 300, rangeMaxBRL: 600, unit: "frasco 2mg liofilizado", source: "Farmácias de manipulação" },
    references: ["Teichman SL et al. (2006). Prolonged stimulation of growth hormone. JCEM."],
  },
  {
    id: "aod9604", name: "AOD-9604",
    aliases: ["Anti-Obesity Drug 9604", "Tyr-hGH 177-191"],
    diagnoses: ["obesidade", "obesity", "gordura localizada", "sobrepeso", "emagrecimento", "perder barriga", "queima de gordura", "metabolismo lento", "lipodistrofia", "cartilagem", "osteoartrite"],
    mechanism: "Fragmento C-terminal do Hormônio do Crescimento (aminoácidos 177-191). Estimula a lipólise (quebra de gordura) e inibe a lipogênese (formação de gordura) sem afetar os níveis de açúcar no sangue ou o crescimento tecidual.",
    dosage: "300 mcg a 1 mg/dia (frequentemente em jejum)", route: "Subcutânea", cycle: "4–12 semanas",
    benefits: ["Mobilização agressiva de gordura (especialmente visceral)", "Não afeta a glicemia ou resistência à insulina", "Propriedades regenerativas na cartilagem (osteoartrite)"],
    sideEffects: ["Leve vermelhidão no local", "Dor de cabeça ocasional"],
    contraindications: ["Gravidez e lactação"],
    evidenceLevel: "Fase II Clínica / Status GRAS pela FDA",
    pricing: { averageMonthlyBRL: 500, averageMonthlyUSD: 100, rangeMinBRL: 350, rangeMaxBRL: 700, unit: "frasco 5mg", source: "Importação e manipulação" },
    references: ["Stommaco et al. (2001). AOD9604 and lipid metabolism."],
  },
  {
    id: "melanotanii", name: "Melanotan II",
    aliases: ["MT2", "MT-II"],
    diagnoses: ["vitiligo", "bronzeamento", "proteção solar", "pele pálida", "falta de libido", "disfunção erétil", "impotência", "baixa libido", "câncer de pele (prevenção)", "queimadura solar"],
    mechanism: "Análogo sintético do hormônio alfa-estimulante de melanócitos (α-MSH). Estimula fortemente a produção de melanina (pigmentação) e atua nos receptores de melanocortina no cérebro, ativando a excitação sexual.",
    dosage: "100–500 mcg/dia (doses gradativas)", route: "Subcutânea", cycle: "2–4 semanas (fase de saturação) + Manutenção",
    benefits: ["Bronzeamento profundo e duradouro sem alta exposição solar", "Aumento drástico e espontâneo da libido e ereções", "Proteção contra danos UV em pessoas de pele clara", "Inibição de apetite moderada"],
    sideEffects: ["Náusea intensa nos primeiros dias", "Escurecimento de pintas e sardas", "Ereções prolongadas", "Rubor"],
    contraindications: ["Histórico de melanoma", "Doenças cardiovasculares graves"],
    evidenceLevel: "Ensaios clínicos iniciais, uso majoritariamente cosmético/off-label",
    pricing: { averageMonthlyBRL: 350, averageMonthlyUSD: 70, rangeMinBRL: 250, rangeMaxBRL: 500, unit: "frasco 10mg", source: "Importação" },
    references: ["Wessells H et al. (1998). Synthetic melanotropic peptide initiates erections. J Urol."],
  },
  {
    id: "semax", name: "Semax",
    aliases: ["Heptapeptídeo ACTH(4-10)"],
    diagnoses: ["tdah", "adhd", "foco", "falta de atenção", "névoa mental", "brain fog", "fadiga mental", "AVC", "recuperação de derrame", "estresse neurogênico", "glaucoma ótico", "memória", "nootrópico", "produtividade"],
    mechanism: "Heptapeptídeo sintético baseado no hormônio adrenocorticotrófico (ACTH). Eleva dramaticamente o BDNF no cérebro, protege neurônios de danos isquêmicos e modula receptores dopaminérgicos e serotoninérgicos.",
    dosage: "200–1000 mcg/dia", route: "Intranasal (gotas ou spray) ou Subcutânea", cycle: "2–6 semanas",
    benefits: ["Nootrópico poderoso (aumento imediato de foco e clareza)", "Recuperação acelerada após AVC (uso clínico na Rússia)", "Alívio rápido do TDAH sem os efeitos colaterais de estimulantes", "Neurogênese e proteção contra hipóxia"],
    sideEffects: ["Leve irritabilidade (raro)", "Queda de cabelo relatada anedoticamente em uso crônico extremo"],
    contraindications: ["Psicoses ativas", "Transtorno bipolar em fase de mania"],
    evidenceLevel: "Medicamento aprovado na Rússia (Lista de Medicamentos Essenciais)",
    pricing: { averageMonthlyBRL: 450, averageMonthlyUSD: 90, rangeMinBRL: 300, rangeMaxBRL: 600, unit: "spray nasal 0.1% / 1%", source: "Farmácias russas e internacionais" },
    references: ["Gusev EI et al. (2018). Semax in treatment of stroke."],
  },
  {
    id: "selank", name: "Selank",
    aliases: ["Tuftsin analogue"],
    diagnoses: ["ansiedade", "anxiety", "estresse", "stress", "insônia tensional", "síndrome do pânico", "pânico", "transtorno de ansiedade generalizada", "tag", "fobia social", "depressão leve", "falta de calma"],
    mechanism: "Peptídeo ansiolítico que estabiliza as encefalinas no cérebro e modula o sistema GABAérgico (similar aos benzodiazepínicos, mas sem sedação ou risco de vício).",
    dosage: "200–500 mcg/dia", route: "Intranasal (spray)", cycle: "2–4 semanas ou sob demanda",
    benefits: ["Efeito calmante imediato e potente", "Zero sedação, mantendo a lucidez e cognição", "Não causa tolerância ou síndrome de abstinência", "Melhora do humor e alívio do pânico"],
    sideEffects: ["Mínimos ou inexistentes", "Leve irritação nasal"],
    contraindications: ["Nenhuma absoluta descrita (hipersensibilidade)"],
    evidenceLevel: "Medicamento aprovado na Rússia",
    pricing: { averageMonthlyBRL: 450, averageMonthlyUSD: 90, rangeMinBRL: 300, rangeMaxBRL: 600, unit: "spray nasal 0.15%", source: "Importação" },
    references: ["Zozulya AA et al. (2001). The inhibitory effect of Selank on enkephalin-degrading enzymes."],
  },
  {
    id: "motsc", name: "MOTS-c",
    aliases: ["Mitochondrial Derived Peptide"],
    diagnoses: ["obesidade", "resistência à insulina", "diabetes tipo 2", "fadiga crônica", "falta de energia", "cansaço extremo", "performance esportiva", "metabolismo", "doença mitocondrial", "sedentarismo"],
    mechanism: "Peptídeo derivado da mitocôndria. Atua como um mimetizador de exercícios físicos (exercise mimetic), ativando a enzima AMPK. Reprograma o metabolismo para queimar gordura e melhora a sensibilidade à insulina muscular.",
    dosage: "10 mg uma vez por semana", route: "Subcutânea", cycle: "4–8 semanas",
    benefits: ["Mimetiza os efeitos metabólicos do exercício físico", "Reverte resistência à insulina promovendo captação de glicose muscular", "Aumento drástico de energia celular e mitocondrial", "Aceleração da queima de gordura e sobrevida (em ratos)"],
    sideEffects: ["Dor leve no local da injeção", "Aumento temporário do suor"],
    contraindications: ["Falta de dados em gravidez e doenças renais severas"],
    evidenceLevel: "Pré-clínico avançado / Estudos fase I",
    pricing: { averageMonthlyBRL: 1200, averageMonthlyUSD: 240, rangeMinBRL: 800, rangeMaxBRL: 1600, unit: "frasco 10mg", source: "Importação especializada" },
    references: ["Lee C et al. (2015). The Mitochondrial-Derived Peptide MOTS-c Promotes Metabolic Homeostasis. Cell Metab."],
  },
  {
    id: "tesamorelin", name: "Tesamorelin",
    aliases: ["Egrifta", "TH9507"],
    diagnoses: ["gordura visceral", "lipodistrofia", "barriga grande", "obesidade central", "deficiência de gh", "anti-aging", "triglicerídeos altos", "síndrome metabólica", "esteatose", "fígado gordo"],
    mechanism: "Análogo sintético do hormônio liberador do hormônio de crescimento (GHRH). É o peptídeo mais potente para estimular a redução isolada e focada da gordura visceral (gordura dura intra-abdominal).",
    dosage: "1–2 mg/dia", route: "Subcutânea", cycle: "12–24 semanas",
    benefits: ["Redução comprovada de 15% a 20% da gordura visceral em meses", "Redução do tecido adiposo no fígado (esteatose)", "Melhora do perfil lipídico", "Aprovado pelo FDA"],
    sideEffects: ["Dor articular leve", "Aumento da glicemia em pacientes predispostos", "Retenção de fluidos", "Vermelhidão (Eritema)"],
    contraindications: ["Câncer ativo", "Gravidez", "Retinopatia diabética severa"],
    evidenceLevel: "FDA aprovado (para lipodistrofia associada ao HIV)",
    pricing: { averageMonthlyBRL: 2500, averageMonthlyUSD: 500, rangeMinBRL: 1500, rangeMaxBRL: 4000, unit: "frasco 2mg liofilizado", source: "Mercado farmacêutico (Egrifta) e Manipulação" },
    references: ["Falutz J et al. (2007). Effects of TH9507, a growth hormone releasing factor analog. JCEM."],
  },
  {
    id: "ll37", name: "LL-37",
    aliases: ["Cathelicidin antimicrobial peptide"],
    diagnoses: ["doença autoimune", "infecção crônica", "candidiase", "lyme", "doença de lyme", "artrite reumatoide", "lupus", "inflamação sistêmica", "cicatrização difícil", "disbiose intestinal", "superbactéria"],
    mechanism: "Peptídeo antimicrobiano humano natural (Catelicidina). Possui propriedades antivirais, antibacterianas e antifúngicas destrutivas para membranas patogênicas, além de ser um imunomodulador potente em autoimunidades.",
    dosage: "200–500 mcg (dias alternados)", route: "Subcutânea", cycle: "4–6 semanas",
    benefits: ["Destrói biofilmes de bactérias resistentes", "Modula o sistema imunológico reprimindo respostas autoimunes (artrite, lúpus)", "Acelera cicatrização de úlceras e feridas infectadas", "Atuação eficiente contra a doença de Lyme"],
    sideEffects: ["Dor severa no local da aplicação", "Febre leve temporária (resposta imune)"],
    contraindications: ["Hipersensibilidade severa", "Uso prolongado sem acompanhamento"],
    evidenceLevel: "Fase pré-clínica clínica emergente",
    pricing: { averageMonthlyBRL: 800, averageMonthlyUSD: 160, rangeMinBRL: 600, rangeMaxBRL: 1200, unit: "frasco 5mg", source: "Fornecedores de pesquisa" },
    references: ["Vandamme D et al. (2012). The diverse roles of LL-37 in health and disease."],
  },
  {
    id: "cerebrolysin", name: "Cerebrolysin",
    aliases: ["Cerebrolisina", "FPF 1070"],
    diagnoses: ["demência", "alzheimer", "avc", "derrame", "tbi", "trauma cranioencefálico", "lesão cerebral", "declínio cognitivo", "névoa mental", "autismo", "neuropatia", "déficit motor"],
    mechanism: "Mistura neuropeptídica purificada de cérebros suínos. Simula os fatores neurotróficos (BDNF, GDNF, NGF). Promove neurogênese estrutural, sobrevivência neuronal e reparo em larga escala do cérebro danificado.",
    dosage: "5 a 20 ml/dia", route: "Intramuscular ou Intravenosa (infusão lenta)", cycle: "4 semanas (diariamente ou 5x semana)",
    benefits: ["Tratamento neuro-reparador comprovado para AVC isquêmico e Trauma Craniano", "Retarda o avanço da demência e Alzheimer", "Gera novas conexões sinápticas (neuroplasticidade estrutural)", "Melhora da função motora e cognitiva pós-acidente"],
    sideEffects: ["Sensação de calor", "Leve agitação", "Tontura durante infusão IV rápida"],
    contraindications: ["Epilepsia severa", "Insuficiência renal grave", "Alergia a proteínas suínas"],
    evidenceLevel: "Fase IV / Aprovado clinicamente em dezenas de países (Europa, Ásia)",
    pricing: { averageMonthlyBRL: 1200, averageMonthlyUSD: 240, rangeMinBRL: 800, rangeMaxBRL: 2000, unit: "ampolas 10ml (cx com 5)", source: "Farmácias internacionais" },
    references: ["Bornstein NM et al. (2018). Cerebrolysin in Acute Ischemic Stroke. Stroke."],
  },
  {
    id: "kisspeptin10", name: "Kisspeptin-10",
    aliases: ["Metastin", "KISS1"],
    diagnoses: ["baixa testosterona", "hipogonadismo", "infertilidade", "atrofia testicular", "libido baixa", "impotência", "terapia pós ciclo", "tpc", "regulação hormonal"],
    mechanism: "Estimulador do eixo hipotálamo-hipófise-gonadal. A Kisspeptina aciona diretamente a liberação do GnRH (Hormônio Liberador de Gonadotrofina), que instrui o corpo a produzir seu próprio LH, FSH e Testosterona em homens e mulheres.",
    dosage: "100–300 mcg/dia", route: "Subcutânea", cycle: "4–8 semanas",
    benefits: ["Aumenta drasticamente a testosterona natural (ao contrário de esteroides sintéticos)", "Preserva e aumenta a fertilidade e tamanho gonadal", "Melhora o humor e o desejo sexual", "Auxilia na Terapia Pós-Ciclo (TPC) para recuperação de eixo hormonal"],
    sideEffects: ["Ondas de calor", "Flutuações emocionais temporárias", "Fadiga leve inicial"],
    contraindications: ["Câncer de próstata sensível a hormônios", "Câncer de mama", "Gravidez"],
    evidenceLevel: "Ensaios Clínicos (Fase II)",
    pricing: { averageMonthlyBRL: 550, averageMonthlyUSD: 110, rangeMinBRL: 400, rangeMaxBRL: 900, unit: "frasco 10mg", source: "Mercado magistral/internacional" },
    references: ["Dhillo WS et al. (2005). Kisspeptin-54 stimulates the hypothalamic-pituitary gonadal axis in human males."],
  },
  {
    id: "ara290", name: "ARA-290",
    aliases: ["Cibinetide", "Helix B Surface Peptide"],
    diagnoses: ["dor crônica", "chronic pain", "neuropatia", "neuropatia diabética", "fibromialgia", "sarcoidose", "inflamação de nervos", "reparo de nervos", "dor ciática", "doença autoimune", "fadiga por inflamação"],
    mechanism: "Peptídeo que se liga ao receptor inato de reparo tecidual (IRR), complexo que atua em macrofágos para cessar a produção de citocinas inflamatórias e iniciar a neurogênese, especificamente reparando nervos periféricos danificados.",
    dosage: "4 mg/dia", route: "Subcutânea", cycle: "4 semanas (diário)",
    benefits: ["Reduz e reverte quadros graves de dores neuropáticas", "Estimula a regeneração de pequenas fibras nervosas", "Alivia inflamação e fadiga sistêmica em doenças raras (Sarcoidose)", "Zero efeito imunossupressor (diferente de corticoides)"],
    sideEffects: ["Mínimos (excelente perfil de segurança)", "Irritação local passageira"],
    contraindications: ["Nenhuma conhecida formalmente (restrito por falta de estudos em grávidas)"],
    evidenceLevel: "Fase II/III (Orphan Drug Designation pelo FDA)",
    pricing: { averageMonthlyBRL: 2800, averageMonthlyUSD: 560, rangeMinBRL: 2000, rangeMaxBRL: 4000, unit: "frasco 16mg", source: "Pesquisa / Especializados" },
    references: ["Dahan A et al. (2013). ARA 290 improves symptoms in patients with sarcoidosis. Mol Med."],
  },
  {
    id: "thymosinalpha1", name: "Timosina Alfa-1",
    aliases: ["Thymosin Alpha-1", "TA1", "Zadaxin"],
    diagnoses: ["baixa imunidade", "imunodeficiência", "infecção viral", "hepatite", "doença de lyme", "câncer", "imunidade", "resfriado constante", "fadiga crônica", "hiv", "doença autoimune", "covid longa"],
    mechanism: "Peptídeo endógeno produzido pelo timo. Restaura e modula a função imunológica, estimula a maturação das células T, aumenta a produção de citocinas (como IFN-gama) e melhora a detecção de patógenos e células tumorais pelo corpo.",
    dosage: "1.5 mg duas vezes por semana", route: "Subcutânea", cycle: "4-12 semanas",
    benefits: ["Aumento drástico e seguro da resposta imunológica (células T)", "Aprovado clinicamente para Hepatite B e C (Zadaxin)", "Uso adjuvante em terapias contra o câncer e infecções crônicas graves"],
    sideEffects: ["Irritação no local da injeção", "Fadiga temporária devido à resposta imune"],
    contraindications: ["Pacientes transplantados (risco de rejeição)", "Doenças autoimunes superativas (em alguns casos)"],
    evidenceLevel: "FDA Orphan Drug / Aprovado em 35+ países",
    pricing: { averageMonthlyBRL: 900, averageMonthlyUSD: 180, rangeMinBRL: 700, rangeMaxBRL: 1400, unit: "frasco 10mg", source: "Importação" },
    references: ["Goldstein AL et al. (2004). Thymosin alpha1: chemistry, macrophages, and immunomodulation."],
  },
  {
    id: "kpv", name: "KPV",
    aliases: ["Lys-Pro-Val", "KPV Peptide"],
    diagnoses: ["doença inflamatória intestinal", "crohn", "colite ulcerativa", "sii", "inflamação intestinal", "psoríase", "dermatite", "cândida", "candidiase", "disbiose", "alergia", "urticária"],
    mechanism: "Tripeptídeo C-terminal derivado do hormônio alfa-MSH. É um potente anti-inflamatório sistêmico e antimicrobiano no trato GI e na pele. Não causa hiperpigmentação (diferente do Melanotan).",
    dosage: "200-500 mcg/dia (SC) ou 5-10 mg/dia (Oral)", route: "Oral (cápsulas) ou Subcutânea", cycle: "Uso contínuo ou 4-8 semanas",
    benefits: ["Combate direto a fungos como Candida albicans no intestino", "Redução excepcional da inflamação intestinal (Crohn e Colite)", "Melhora agressiva de quadros de Psoríase e inflamações de pele"],
    sideEffects: ["Extremamente seguro, efeitos colaterais muito raros"],
    contraindications: ["Nenhuma documentada especificamente"],
    evidenceLevel: "Pré-clínico (Roedores) / Relatos clínicos emergentes",
    pricing: { averageMonthlyBRL: 400, averageMonthlyUSD: 80, rangeMinBRL: 300, rangeMaxBRL: 600, unit: "cápsulas orais ou liofilizado", source: "Manipulação / Importação" },
    references: ["Luger TA et al. (2007). The role of alpha-MSH and related peptides in inflammation."],
  },
  {
    id: "hghfrag176191", name: "HGH Frag 176-191",
    aliases: ["AOD-9604 variation", "Fragmento HGH"],
    diagnoses: ["obesidade", "gordura localizada", "emagrecimento", "queima de gordura", "metabolismo lento", "barriga grande", "pneuzinho", "lipólise"],
    mechanism: "Fragmento sintético isolado dos últimos aminoácidos (176-191) do GH humano. É a porção exata do GH responsável apenas pela queima de gordura (lipólise), sem os efeitos de crescimento ósseo ou de resistência à insulina.",
    dosage: "250-500 mcg duas vezes ao dia (em jejum)", route: "Subcutânea", cycle: "4-12 semanas",
    benefits: ["Estimula a queima de gordura 12.5x mais forte que o GH intacto", "Impede a formação de nova gordura (lipogênese)", "Não impacta os níveis de insulina ou glicose"],
    sideEffects: ["Vermelhidão leve no local", "Aumento da sudorese", "Ligeira taquicardia em doses altas"],
    contraindications: ["Gravidez e lactação"],
    evidenceLevel: "Pré-clínico e Fase IIa",
    pricing: { averageMonthlyBRL: 450, averageMonthlyUSD: 90, rangeMinBRL: 350, rangeMaxBRL: 700, unit: "frasco 5mg", source: "Importação" },
    references: ["Ng FM et al. (2000). A truncated fragment of growth hormone with lipolytic activity."],
  },
  {
    id: "dsip", name: "DSIP",
    aliases: ["Delta Sleep-Inducing Peptide"],
    diagnoses: ["insônia", "distúrbio do sono", "ansiedade noturna", "sono leve", "estresse agudo", "abstinência", "dor crônica", "dormir mal"],
    mechanism: "Peptídeo neuromodulador encontrado originalmente no sangue de coelhos durante o sono induzido. Ele ultrapassa a barreira hematoencefálica e promove o sono de ondas lentas (Delta), além de regular a secreção de cortisol.",
    dosage: "100-200 mcg ao deitar", route: "Subcutânea", cycle: "Uso pontual (2-3x na semana)",
    benefits: ["Induz o sono profundo (Delta) reparador", "Melhora do ritmo circadiano de forma não narcótica", "Auxilia clinicamente no alívio de dores e sintomas de abstinência (álcool/opiáceos)"],
    sideEffects: ["Sonolência diurna (se dose muito alta)", "Dor de cabeça"],
    contraindications: ["Narcolepsia", "Uso concomitante com altas doses de sedativos/álcool"],
    evidenceLevel: "Pesquisa humana e uso off-label extensivo",
    pricing: { averageMonthlyBRL: 350, averageMonthlyUSD: 70, rangeMinBRL: 250, rangeMaxBRL: 500, unit: "frasco 2mg", source: "Importação" },
    references: ["Kovalzon VM et al. (1993). DSIP and sleep."],
  },
  {
    id: "igf1lr3", name: "IGF-1 LR3",
    aliases: ["Long Arg3 IGF-1", "Fator de Crescimento Semelhante à Insulina"],
    diagnoses: ["hipertrofia muscular", "crescimento muscular", "perda muscular", "sarcopenia", "atrofia muscular", "recuperação extrema", "desempenho atlético", "fisiculturismo"],
    mechanism: "Análogo sintético do IGF-1 com adição de arginina e extensão da cadeia, impedindo que seja desativado pelas proteínas ligadoras (IGFBPs). Possui meia-vida de 20-30h (contra 20 min do IGF-1 natural). Provoca hiperplasia (criação de novas células musculares).",
    dosage: "20-50 mcg/dia (pós-treino)", route: "Subcutânea ou Intramuscular", cycle: "4-6 semanas (máximo, devido a dessensibilização de receptores)",
    benefits: ["Hiperplasia muscular (multiplicação celular real, não apenas inchaço)", "Recuperação anabólica extremamente rápida", "Melhora incrível da captação de nutrientes e transporte de aminoácidos"],
    sideEffects: ["Hipoglicemia perigosa se usado sem carboidratos", "Potencial de crescimento de órgãos (intestino) e tecidos neoplásicos em abusos", "Retenção hídrica"],
    contraindications: ["Qualquer tipo de câncer ou risco de câncer", "Diabetes mal controlado", "Histórico de cardiomegalia"],
    evidenceLevel: "Uso em pesquisa in vitro / Alta prevalência off-label atlética",
    pricing: { averageMonthlyBRL: 800, averageMonthlyUSD: 160, rangeMinBRL: 600, rangeMaxBRL: 1200, unit: "frasco 1mg liofilizado", source: "Underground / Importação" },
    references: ["Tomas FM et al. (1995). IGF-I variants which bind poorly to IGF-binding proteins show more potent anabolic effects."],
  },
  {
    id: "pegmgf", name: "PEG-MGF",
    aliases: ["Fator de Crescimento Mecânico Peguilado"],
    diagnoses: ["lesão muscular crônica", "hipertrofia localizada", "rasgo no músculo", "recuperação nervosa", "atrofia", "envelhecimento muscular", "estiramento"],
    mechanism: "Variante de splicing (corte) do gene do IGF-1, o MGF atua estimulando as células satélites musculares a se dividirem e repararem danos locais. A 'Peguilação' (adição de polietilenoglicol) prolonga sua vida útil de minutos para dias na corrente sanguínea.",
    dosage: "200-400 mcg, 2-3 vezes por semana (longe dos treinos)", route: "Subcutânea", cycle: "4-6 semanas",
    benefits: ["Reparo e crescimento brutal de células musculares satélites", "Capacidade regenerativa superior para músculos lesionados (rasgos)", "Recuperação neurológica local"],
    sideEffects: ["Crescimento celular desordenado em superdosagem", "Hipoglicemia leve", "Irritação local profunda"],
    contraindications: ["Câncer ativo", "Displasia celular"],
    evidenceLevel: "In Vitro e Pré-clínico em animais",
    pricing: { averageMonthlyBRL: 450, averageMonthlyUSD: 90, rangeMinBRL: 300, rangeMaxBRL: 700, unit: "frasco 2mg", source: "Importação" },
    references: ["Goldspink G. (2005). Mechanical signals, IGF-I gene splicing, and muscle adaptation. Physiology."],
  },
  {
    id: "ghrp6", name: "GHRP-6",
    aliases: ["Growth Hormone Releasing Peptide-6"],
    diagnoses: ["falta de apetite", "anorexia", "desnutrição", "caquexia", "deficiência de gh", "ganho de peso", "perda de massa", "fraqueza extrema"],
    mechanism: "Secretagogo de GH de primeira geração. É um poderoso estimulador do receptor de grelina (hormônio da fome). Além do pico alto de GH, induz uma fome extrema quase instantânea e aumenta motilidade gástrica.",
    dosage: "100-150 mcg (2-3x ao dia)", route: "Subcutânea", cycle: "8-12 semanas",
    benefits: ["Estímulo intenso do apetite (excelente para bulking ou caquexia)", "Pico maciço na secreção endógena de GH", "Reparo de tecidos e articulações", "Proteção neurológica"],
    sideEffects: ["Aumento de prolactina e cortisol (em doses altas)", "Fome incontrolável (desvantagem para obesos)", "Letargia", "Retenção hídrica grave"],
    contraindications: ["Obesidade severa", "Tumores pituitários", "Diabetes descontrolado"],
    evidenceLevel: "Amplo uso clínico e off-label",
    pricing: { averageMonthlyBRL: 300, averageMonthlyUSD: 60, rangeMinBRL: 200, rangeMaxBRL: 450, unit: "frasco 5mg", source: "Importação / Manipulação" },
    references: ["Bowers CY et al. (1984). Synthetic GH-releasing peptides."],
  },
  {
    id: "ghrp2", name: "GHRP-2",
    aliases: ["Pralmorelin", "Growth Hormone Releasing Peptide-2"],
    diagnoses: ["baixa estatura infantil", "deficiência de gh", "sarcopenia", "anti-aging", "recuperação de lesões", "recuperação rápida"],
    mechanism: "Versão de segunda geração do GHRP. Provoca picos de GH mais agressivos que o GHRP-6, mas com menor estímulo aos receptores de grelina (não causa tanta fome). Muito usado no Japão de forma clínica.",
    dosage: "100-200 mcg (2x ao dia)", route: "Subcutânea", cycle: "8-12 semanas",
    benefits: ["Liberação fortíssima de GH endógeno", "Menor aumento de apetite comparado ao GHRP-6", "Aprovado clinicamente (em alguns países asiáticos) para testar a glândula pituitária"],
    sideEffects: ["Pode elevar cortisol e prolactina mais que o Ipamorelin", "Retenção de água", "Adormecimento nas mãos (túnel do carpo temporário)"],
    contraindications: ["Ginecomastia prévia (devido a prolactina)", "Tumores hipofisários"],
    evidenceLevel: "Fase III / Aprovado no Japão",
    pricing: { averageMonthlyBRL: 350, averageMonthlyUSD: 70, rangeMinBRL: 250, rangeMaxBRL: 500, unit: "frasco 5mg", source: "Importação" },
    references: ["Phung LT et al. (2000). The effects of GHRP-2 on GH secretion."],
  },
  {
    id: "sermorelin", name: "Sermorelin",
    aliases: ["Geref", "GRF 1-29"],
    diagnoses: ["anti-aging", "envelhecimento", "qualidade do sono", "insônia", "reposição hormonal idoso", "deficiência de gh", "baixa energia"],
    mechanism: "É a versão sintética dos primeiros 29 aminoácidos do hormônio liberador do hormônio de crescimento humano (GHRH). Tem uma meia-vida curtíssima (10-20 min), induzindo um pico natural suave de GH, imitando a juventude.",
    dosage: "200-500 mcg (antes de dormir)", route: "Subcutânea", cycle: "Uso contínuo ou ciclos de 3-6 meses",
    benefits: ["O secretagogo mais antigo, natural e seguro estudado", "Melhora drástica no sono e vitalidade em idosos", "Rejuvenesce o perfil hormonal noturno", "Nenhum risco de taquifilaxia grave"],
    sideEffects: ["Rubor imediato no rosto e pescoço", "Tontura leve após a injeção"],
    contraindications: ["Neoplasias ativas", "Alergia conhecida"],
    evidenceLevel: "Aprovado pelo FDA (antigamente como Geref) para diagnóstico",
    pricing: { averageMonthlyBRL: 450, averageMonthlyUSD: 90, rangeMinBRL: 350, rangeMaxBRL: 700, unit: "frasco 2mg liofilizado", source: "Farmácias de manipulação" },
    references: ["Walker RF. (2006). Sermorelin: a better approach to management of adult-onset growth hormone failure?"],
  },
  {
    id: "retatrutide", name: "Retatrutida",
    aliases: ["Triple G", "LY3437943"],
    diagnoses: ["obesidade extrema", "obesidade", "emagrecimento", "gordice extrema", "esteatose avançada", "diabetes tipo 2 refratária", "síndrome metabólica grave", "sobrepeso", "perda de peso absurda"],
    mechanism: "O ápice farmacológico moderno (Triple G). É um triplo-agonista atuando nos receptores de GIP, GLP-1 e Glucagon simultaneamente. Além de tirar a fome (GLP-1/GIP), o agonismo do glucagon aumenta o gasto energético basal violentamente.",
    dosage: "1 a 12 mg / semana (incrementos graduais mensais)", route: "Subcutânea", cycle: "Contínuo",
    benefits: ["Perda de peso inédita e chocante na medicina (média de 24,2% em 48 semanas no Fase 2)", "Zera praticamente toda a gordura hepática", "Aumento da taxa metabólica basal de queima calórica"],
    sideEffects: ["Náuseas extremas (se subido rápido)", "Aceleração cardíaca (efeito do glucagon)", "Diarreia e problemas gastrointestinais fortes"],
    contraindications: ["Histórico de pancreatite grave", "Histórico familiar de CMT", "Arritmias cardíacas instáveis"],
    evidenceLevel: "Fase III em andamento (Eficácia monstruosa nos ensaios)",
    pricing: { averageMonthlyBRL: 4500, averageMonthlyUSD: 900, rangeMinBRL: 3000, rangeMaxBRL: 6000, unit: "Pós-Fase 3 (Valores de pesquisa)", source: "Research Chemical (2025)" },
    references: ["Jastreboff AM et al. (2023). Triple–Hormone-Receptor Agonist Retatrutide for Obesity. NEJM."],
  },
  {
    id: "follistatin344", name: "Folistatina-344",
    aliases: ["Follistatin", "Inibidor de Miostatina"],
    diagnoses: ["atrofia muscular extrema", "distrofia muscular", "sarcopenia avançada", "fisiculturismo extremo", "ganho de massa rápido", "mutação genética muscular"],
    mechanism: "Glicoproteína autácrina que se liga à Miostatina (o freio genético do crescimento muscular) e a neutraliza completamente. Isso destrava o limite genético de ganho de massa magra do indivíduo de forma agressiva.",
    dosage: "100 mcg / dia por 10-20 dias (microciclos)", route: "Subcutânea (ou intramuscular local)", cycle: "Máximo 10-20 dias por vez",
    benefits: ["Ganhos maciços de hipertrofia em curtíssimo tempo (animal model)", "Aumento radical de força e densidade óssea", "Tratamento experimental promissor para Distrofias Musculares"],
    sideEffects: ["Crescimento cardíaco (hipertrofia miocárdica) em abusos prolongados", "Estiramentos de tendão (o músculo cresce mais rápido que o tendão aguenta)"],
    contraindications: ["Doenças cardiovasculares e arritmias", "Menores com tecido em desenvolvimento"],
    evidenceLevel: "Pré-clínico (Estudos Animais) / Terapias genéticas experimentais (Fase I/II)",
    pricing: { averageMonthlyBRL: 1500, averageMonthlyUSD: 300, rangeMinBRL: 1000, rangeMaxBRL: 2000, unit: "frasco 1mg", source: "Underground Research" },
    references: ["Rodino-Klapac LR et al. (2009). Inhibition of myostatin with emphasis on follistatin as a therapy for muscle disease."],
  },
  {
    id: "adipotide", name: "Adipotide",
    aliases: ["FTPP", "Fat Targeted Proapoptotic Peptide"],
    diagnoses: ["obesidade refratária", "gordura visceral", "gordura localizada", "perda de peso severa", "barriga grande"],
    mechanism: "Peptídeo proapoptótico. Diferente de hormônios, ele circula no sangue e se liga APENAS aos vasos sanguíneos que alimentam as células de gordura branca. Ele bloqueia o sangue, sufocando as células de gordura, matando-as (apoptose). O corpo então as reabsorve.",
    dosage: "Experimental em animais (0.43 mg/kg)", route: "Subcutânea", cycle: "Micros ciclos estritos (3-4 semanas)",
    benefits: ["Morte direta (apoptose) de células adiposas maduras", "Perda de peso absurdamente rápida em modelos símios", "Destruição permanente dos estoques viscerais"],
    sideEffects: ["Danos renais irreversíveis (lesões tubulares) documentados em animais e macacos", "Desidratação extrema", "Dores articulares sistêmicas"],
    contraindications: ["Não aprovado para humanos. Uso proibido sem acompanhamento científico de altíssimo risco."],
    evidenceLevel: "Apenas Pesquisa Animal (Macacos e Roedores). Ensaios em humanos paralisados por toxicidade.",
    pricing: { averageMonthlyBRL: 2000, averageMonthlyUSD: 400, rangeMinBRL: 1500, rangeMaxBRL: 3000, unit: "frasco para pesquisa experimental", source: "E-commerces de pesquisa asiáticos" },
    references: ["Barnhart KF et al. (2011). A peptidomimetic targeting white fat causes weight loss and improved insulin resistance in obese monkeys."],
  },
  {
    id: "vip", name: "VIP",
    aliases: ["Vasoactive Intestinal Peptide"],
    diagnoses: ["doença de lyme crônica", "síndrome de fadiga crônica", "mofo", "doença inflamatória intestinal", "cirs", "síndrome de resposta inflamatória crônica", "asma", "falta de ar", "disfunção imunológica profunda"],
    mechanism: "Neurotransmissor peptídico que relaxa os vasos sanguíneos (vasodilatador), a musculatura lisa bronquial, e reduz massivamente as citocinas inflamatórias nos pulmões e cérebro. Restaura o ritmo circadiano e modula a imunidade cerebral.",
    dosage: "50 mcg (4x ao dia)", route: "Intranasal (spray)", cycle: "Uso contínuo crônico sob supervisão",
    benefits: ["Padrão ouro (Protocolo Shoemaker) para pacientes expostos a biotoxinas e mofo tóxico", "Reversão da atrofia cerebral documentada em CIRS", "Relaxamento pulmonar potente, alívio de dispneia", "Acalma neuroinflamações profundas"],
    sideEffects: ["Queda drástica de pressão arterial (hipotensão)", "Taquicardia reflexa", "Níveis alterados de lípase"],
    contraindications: ["Hipotensão severa prévia", "Uso indiscriminado sem diagnóstico preciso"],
    evidenceLevel: "Fase Clínica / Protocolos validados off-label (Shoemaker Protocol)",
    pricing: { averageMonthlyBRL: 800, averageMonthlyUSD: 160, rangeMinBRL: 600, rangeMaxBRL: 1100, unit: "spray nasal", source: "Farmácias de manipulação especializadas" },
    references: ["Shoemaker RC et al. (2013). Intranasal VIP safely restores volume to multiple grey matter nuclei in patients with CIRS."],
  },
];

if (typeof module !== "undefined") module.exports = { PRODUCTS, CALC_CONFIG, WHATSAPP_NUMBER };
